eureka:
    client:
        region: default
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/

spring:
    application:
        name: cloud_launcher

server.port: 9999


management:
    endpoints:
        web:
            exposure:
                include: "*"


config:
    path: /home/geordie/桌面/config