eureka:
    client:
        region: default
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8082/eureka/

spring:
    application:
        name: testConfig