server:
    port: 8081

spring:
    application:
        name: config
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/config
    profiles:
        active: native
