spring:
  application:
    name: app
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411/

page:
  helloMsg: "my name is geordie"
