spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

eurekaServer:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:${eurekaServer.port}/eureka/