server:
  port: 8085

spring:
  application:
    name: gateway

  cloud:
    config:
      name: gateway

    gateway:
      routes:
        - id: app_router
          uri: lb://app
          predicates:
            - Path=/spring-app
          filters:
            - StripPrefix=1
