server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app_router
          uri: lb://app
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
        - id: feign_router
          uri: lb://feign
          predicates:
             - Path=/feign/**
          filters:
            - StripPrefix=1
